//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlifransShopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalhesCompra
    {
        public int DetalhesCompraId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<double> Valorpago { get; set; }
        public string FormaDePagamento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
