//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlifransShopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identificacao
    {
        public int IdentificacaoId { get; set; }
        public string IdentificacaoNome { get; set; }
    }
}
