//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlifransShopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Carrinho = new HashSet<Carrinho>();
        }
    
        public int ProdutoId { get; set; }
        public string ProdutoNome { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public Nullable<bool> StatusAtivo { get; set; }
        public Nullable<bool> StatusDelete { get; set; }
        public Nullable<System.DateTime> CriadoData { get; set; }
        public Nullable<System.DateTime> ModificadoData { get; set; }
        public string Descricao { get; set; }
        public string ProdutoImage { get; set; }
        public Nullable<bool> EmDestaque { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<double> PrecoUnitario { get; set; }
        public Nullable<double> PrecoTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
